name: Deploy Website
on:
  push:
    branches: [master]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Publish ${{ github.ref }}
        run: sbt docs/docusaurusPublishGhpages
        env:
          GITHUB_DEPLOY_KEY: ${{ secrets.DOC }}